In [1]:
import numpy as np

In [6]:
np.zeros(2,)

array([0., 0.])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full((2,2), 5)

array([[5, 5],
       [5, 5]])

In [16]:
np.arange(1,10,5)

array([1, 6])

In [17]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [26]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [38]:
a = np.arange(10,200,20)
print(a)
print(a.reshape(2,5))
print(a.ndim)

[ 10  30  50  70  90 110 130 150 170 190]
[[ 10  30  50  70  90]
 [110 130 150 170 190]]
1


In [39]:
a.size

10