In [1]:
import numpy as np

In [2]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
idx = [1,2,3]
a[a > 2]

array([3, 4, 5, 6, 7, 8])

In [6]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.array([40,50,60])

In [10]:
arr2.shape

(3,)

In [ ]:
arr1+arr2

array([[40, 51, 62],
       [43, 54, 65],
       [46, 57, 68]])

In [12]:
arr1+arr2.reshape(1,3)

array([[40, 51, 62],
       [43, 54, 65],
       [46, 57, 68]])