In [1]:
import numpy as np

In [2]:
a = np.array([2,4,6,89,9,1,2,23,65])
print(a)

[ 2  4  6 89  9  1  2 23 65]


In [3]:
b = a.reshape(3,3)
b

array([[ 2,  4,  6],
       [89,  9,  1],
       [ 2, 23, 65]])

In [6]:
a[2] = 300
a

array([  2,   4, 300,  89,   9,   1,   2,  23,  65])

In [8]:
c = b.ravel()
d = b.flatten()


In [10]:
a[2] = 400
c, d

(array([  2,   4, 400,  89,   9,   1, 400, 400, 400]),
 array([  2,   4, 300,  89,   9,   1,   2,  23,  65]))

In [13]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
arr_resized = np.resize(arr,(3,4))
arr_resized

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr[2] = 2000
arr

array([   1,    2, 2000,    4,    5,    6,    7,    8,    9,   10,   11,
         12])

In [17]:
arr_resized

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr_reshaped = arr.reshape(3,4)
arr_reshaped


array([[   1,    2, 2000,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

In [19]:
arr[2] = 3
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
arr_reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
arr_1 = np.arange(1,17).reshape(4,4)
arr_1[2]*=10
arr_1[-1] = arr_1[0]*(-1)
arr_1

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [ 90, 100, 110, 120],
       [ -1,  -2,  -3,  -4]])

In [27]:
arr_1_ravel = arr_1.ravel()
arr_1_ravel

array([  1,   2,   3,   4,   5,   6,   7,   8,  90, 100, 110, 120,  -1,
        -2,  -3,  -4])

In [28]:
arr_1[2,3] = 60546
arr_1

array([[    1,     2,     3,     4],
       [    5,     6,     7,     8],
       [   90,   100,   110, 60546],
       [   -1,    -2,    -3,    -4]])

In [29]:
arr_1_ravel

array([    1,     2,     3,     4,     5,     6,     7,     8,    90,
         100,   110, 60546,    -1,    -2,    -3,    -4])

In [30]:
arr_1_flatten = arr_1.flatten()
arr_1_flatten

array([    1,     2,     3,     4,     5,     6,     7,     8,    90,
         100,   110, 60546,    -1,    -2,    -3,    -4])

In [31]:
arr_1[2,3] = 120
arr_1

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [ 90, 100, 110, 120],
       [ -1,  -2,  -3,  -4]])

In [32]:
arr_1_flatten

array([    1,     2,     3,     4,     5,     6,     7,     8,    90,
         100,   110, 60546,    -1,    -2,    -3,    -4])

In [43]:
a = np.arange(1,5).reshape(2,2)
b = np.array([5,6])
a, b

(array([[1, 2],
        [3, 4]]),
 array([5, 6]))

In [46]:
np.hstack([a, b.reshape(2,1)])

array([[1, 2, 5],
       [3, 4, 6]])

In [48]:
np.hsplit(np.vstack([a, b]), 2)

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]