In [1]:
import numpy as np

In [3]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [4]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [5]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [6]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17])

In [15]:
a = np.array([3, 1])
b = np.array([1,2])
np.linalg.solve(a,b)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional