In [2]:
import numpy as np

In [8]:
a = np.array([312,21,46,54,8,56,-1,92,65,2,31])
a

array([312,  21,  46,  54,   8,  56,  -1,  92,  65,   2,  31])

In [9]:
a[[1,2,3,8,9]]

array([21, 46, 54, 65,  2])

In [11]:
a = np.arange(1,10).reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a[[1,2],[0,1]]

array([4, 8])

In [16]:
a[a<5]

array([1, 2, 3, 4])

In [18]:
a = np.array([[[12,34,64],[123,46,5],[6453,87,6534],[32,654,465]]])
a

array([[[  12,   34,   64],
        [ 123,   46,    5],
        [6453,   87, 6534],
        [  32,  654,  465]]])

In [21]:
# even_a = 
np.where(a%2 == 0, 1, 0)

array([[[1, 1, 1],
        [0, 1, 0],
        [0, 0, 1],
        [1, 1, 0]]])

In [35]:
marks = np.arange(1, 684, 46).reshape(5,3)
marks

array([[  1,  47,  93],
       [139, 185, 231],
       [277, 323, 369],
       [415, 461, 507],
       [553, 599, 645]])

In [ ]:
np.sort(marks)

array([[553, 599, 645],
       [415, 461, 507],
       [277, 323, 369],
       [139, 185, 231],
       [  1,  47,  93]])

In [48]:
a = np.random.randint(1,100, 20)
a


array([83, 94,  3, 63, 52, 40, 63, 63, 46, 48, 78, 64, 90, 42, 15, 20, 89,
       13,  1, 73])

In [50]:
np.select([a<30, (a>30) & (a<70), a>70], ['Low', 'Medium', 'High'])

array(['High', 'High', 'Low', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'High', 'Medium', 'High', 'Medium',
       'Low', 'Low', 'High', 'Low', 'Low', 'High'], dtype='<U6')

In [51]:
import pandas as pd
titanic_df = pd.read_csv('C:/Users/SUNIL/Desktop/G34-Python/Theory/Titanic-Dataset.csv')

In [52]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [56]:
age = titanic_df['Age'].values
np.where(age>50, 1, 0).sum()

64

In [59]:
fare = titanic_df['Fare'].values
fare.mean()

32.204207968574636

In [62]:
(age> 50).sum()

64